# generated by datamodel-codegen:
#   filename:  agent-event.schema.json
#   timestamp: 2026-05-03T19:19:21+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Kind(StrEnum):
    stage_started = 'stage_started'
    stage_finished = 'stage_finished'
    stage_failed = 'stage_failed'
    tool_call_started = 'tool_call_started'
    tool_call_finished = 'tool_call_finished'
    agent_message = 'agent_message'
    plan_ready = 'plan_ready'
    escalation_raised = 'escalation_raised'


class Agent(StrEnum):
    prioritizer = 'prioritizer'
    allocator = 'allocator'
    justifier = 'justifier'
    escalator = 'escalator'
    watch_commander = 'watch_commander'


class AgentEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    ts: float
    agent: Agent | None = None
    tool: str | None = None
    args: dict[str, Any] | None = None
    result_summary: str | None = None
    ms: int | None = None
    preview: str | None = None
    full_id: str | None = None
    tokens: int | None = None
    output_summary: str | None = None
    plan_id: str | None = None
    plan: dict[str, Any] | None = Field(
        None,
        description='Full ResponsePlan body, present on plan_ready events so the console can render without a separate fetch.',
    )
    reason: str | None = None
    error: str | None = None
