# generated by datamodel-codegen:
#   filename:  response-plan.schema.json
#   timestamp: 2026-05-03T19:19:22+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, conint


class Mode(StrEnum):
    kinetic = 'kinetic'
    rf_jam = 'rf_jam'
    spoof = 'spoof'
    monitor = 'monitor'


class Justification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshot_refs: list[str]
    tavily_refs: list[str]
    policy_refs: list[str]


class Assignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target_id: str
    interceptor_id: str
    mode: Mode
    priority: conint(ge=1)
    justification: Justification


class Escalation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    required: bool
    reasons: list[str]


class ResponsePlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    plan_id: str
    snapshot_id: str
    ts: float
    assignments: list[Assignment]
    escalation: Escalation
