# generated by datamodel-codegen:
#   filename:  sensor-message.schema.json
#   timestamp: 2026-05-03T20:53:21+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat


class Detection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    class_: str = Field(..., alias='class')
    conf: confloat(ge=0.0, le=1.0)
    bearing_deg: float
    elev_deg: float
    px_box: list[float] = Field(..., max_length=4, min_length=4)


class SensorMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    node_id: str
    ts: float
    detections: list[Detection]
