# generated by datamodel-codegen:
#   filename:  snapshot.schema.json
#   timestamp: 2026-05-03T20:53:23+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat


class Origin(StrEnum):
    real = 'real'
    simulated = 'simulated'


class Track(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    origin: Origin
    pos_3d: list[float] = Field(..., max_length=3, min_length=3)
    vel: list[float] = Field(..., max_length=3, min_length=3)
    conf: confloat(ge=0.0, le=1.0)
    nearest_asset_m: float | None = None


class Snapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    snapshot_id: str
    ts: float
    tracks: list[Track]
